name: flutter_prakash
description: "Tedious tasks in flutter made easy."
version: 0.0.2
homepage: "https://github.com/prakashbahadurchand/flutter_prakash"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  # External Dependencies
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.prakashbahadurchand.flutter_prakash
        pluginClass: FlutterPrakashPlugin
      ios:
        pluginClass: FlutterPrakashPlugin
