name: flutter_prakash
description: "Tedious tasks in flutter made easy."
version: 0.0.3
homepage: "https://github.com/prakashbahadurchand/flutter_prakash"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  # External Dependencies
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  nepali_date_picker: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.prakashbahadurchand.flutter_prakash
        pluginClass: FlutterPrakashPlugin
      ios:
        pluginClass: FlutterPrakashPlugin
